trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'release'
  MAJOR_VERSION: '0'
  MINOR_VERSION: '1'
  PATCH_VERSION: $[format('{0:yyyyMMdd}', pipeline.startTime)]
  BUILD_VERSION: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 100)]
  CI_BUILD: 'y'

steps:
  - task: CmdLine@2
    inputs:
      script: 'echo "$PATCH_VERSION"'
  - task: DotNetCoreCLI@2
    name: 'Build'
    inputs:
      projects: '**/*.csproj'
      command: build
      arguments: '-c $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    name: 'Test'
    inputs:
      command: test
      projects: '**/*Test/*.csproj'
      arguments: '--configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    name: 'Package'
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: off
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '2f2413e3-c8b9-4082-8831-3a625fec4e55/a0367acd-f673-4d8b-953d-0d255e53f1e3'