trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      projects: '**/*.csproj'
      command: build
      arguments: '-c $(buildConfiguration)'
      
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*Test/*.csproj'
      arguments: '--configuration $(buildConfiguration)'